### ISSUE TITLE
Can't use local html file to follow along from '11. Working with Real Data' onwards - need to setup CORS

### ISSUE THREAD

**Issue by dflock** [hootlex/the-majesty-of-vuejs-2#15]
The text doesn't mention this at all - it reads as if you can just carry on using the local `file://` .html files to try things out, as I'd been doing throughout the rest of the book.

If you want to use a local .html file opened via a `file://` url in the browser, you need to make the following changes:

## the-majesty-of-vuejs-2/apis/stories/public/index.php

Add these lines at the top, just after the `<?php` line:

```
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PATCH, DELETE");
header("Access-Control-Allow-Headers: Content-Type");
```

and them in your local vuejs .html file, point it at `'http://localhost:3000/api/stories' instead of `'/api/stories'``:

```
...
mounted() {
      $.get('http://localhost:3000/api/stories', function(data){
        vm.stories = data;
      })
    },
...
```

and then it'll work - otherwise you'll get CORs errors, or you need to serve your `.html` file from the same server as the API - which you could do by putting it in the `the-majesty-of-vuejs-2/apis/stories/public` folder; indeed there's already one in there - but the text of the book doesn't tell you that - the only clue in the book is that the URL in the browser screenshots changes to `localhost:3000/stories/html`.

**Comment by dflock** [comment]
Adding some more headers as I progress through the following sections.

**Comment by dflock** [comment]
I'm not going to submit a pull request for this because I don't know the proper way to do this in Laravel - the solution above works, but is obviously not the "correct" way to do this.

**Comment by hootlex** [comment]
Hey Duncan, thanks for taking the time to point these out.
For this issue, you can submit a PR to this repo which actually contains the Laravel projects.

If you want to note something that isn't open source you can either open an issue here or send us an email at `hello@tmvuejs.com`.

Thanks a lot for your help.

**Comment by dflock** [comment]
I'm not going to submit a pull request for this because I don't know the proper way to do this in Laravel - the solution above works, but is obviously not the "correct" way to do this.

**Comment by hootlex** [comment]
@dflock okay, I will update project's code soon. :)

**Comment by hootlex** [comment]
In case you are curious, [here is a way](http://stackoverflow.com/questions/33076705/laravel-5-1-api-enable-cors/33090515#33090515) to enable CORS in Laravel.

**Comment by dflock** [comment]
Just got to `12.6.3 Your Code` in the book, where it finally tells you to do this the other way (put your stuff on the server) - but doesn't explain why you might do this.

**Comment by gwvt** [comment]
It would be great to have the code work for local files without any modification. Most readers will be using a local environment rather than putting files on a server, and many will not know PHP.

**Comment by loki-one** [comment]
The headers thing worked :) I was stuck at this point too thank you @dflock  💯
