### ISSUE TITLE
Range v-for cap 4

### ISSUE THREAD

**Issue by Mdpproduction** [hootlex/the-majesty-of-vuejs-2#2]
Hi guys, reading the book, i notice that, when i use a number instead of array/object with v-for directive, "i" doesn't start from 0, but instead is equal to 1. And i'm using vue 2.0.3. There's something that i missing ?

**Comment by pongoman** [comment]
Hello, no you are probably correct, there was a mistake. If you download a new version you will see that it is now fixed.
Thank you, enjoy reading.
