### ISSUE TITLE
Need help with Homework 8

### ISSUE THREAD

**Issue by Dayfiri** [hootlex/the-majesty-of-vuejs-2#20]
I stumble upon problem when doing [this](https://github.com/hootlex/the-majesty-of-vuejs-2/blob/master/homework/chapter8.html) assignment.
I was working by the given example and after running the code I received the error:
![screenshot from 2017-01-04 20-28-57](https://cloud.githubusercontent.com/assets/16082563/21655995/8763389c-d2bc-11e6-9327-9895b47d2f6a.png)
I've even put `action` as a **prop** but that error persisted still. 
I'm new with Vue so it is probably my fault but non to less can someone help me with it, I would be really grateful.

**Comment by Dayfiri** [comment]
So I fixed the problem with this way.
**main.js**
```
action: function(bejb){
      if(this.noChariot){
        this.choice.bejb = 'Pick Chariot'
      }
      else if(this.isCurrent){
        this.choice.bejb = 'Riding'
      }
      else if(this.hasMoreHorses){
        this.choice.bejb = 'Hire Horses'
      }
      else{
        this.choice.bejb = 'Dismiss Horses'
      }
      return this.choice.bejb;
    }
```
Where `choice` and `bejb` are both **props** .
**Choice** -> represents object inside array of object. ( it represents 1 by 1 object with `name` and `horses` )

**Comment by pongoman** [comment]
Hi,
glad to see that you fixed it. Could you provide more info on the environment you are running this(version of Vue, on a single HMTL file, using webpack templates or something similar)?

**Comment by Dayfiri** [comment]
Hi,
Here are some specs I'm working on/with.
OS: Linux Mint 18
Working environment - [here](https://github.com/Dayfiri/Vue)

**Comment by pongoman** [comment]
Thanks, I 'll look into it and maybe add a suggestion in the book with your solution.
