### ISSUE TITLE
Setting up API environment

### ISSUE THREAD

**Issue by Dayfiri** [hootlex/the-majesty-of-vuejs-2#22]
After running script ( sh setup.sh ), this is what I got at the end.
![screenshot from 2017-01-17 19-28-55](https://cloud.githubusercontent.com/assets/16082563/22034116/623fa904-dceb-11e6-9687-1165547fc0c4.png)
Everything else went alright. I never worked with PHP and I don't want to change anything before asking here because there are many "solutions" on the internet and who knows which one is right for my case.
Anyway please help if you can :)

**Comment by andyklimczak** [comment]
After some digging, I have it working using archlinux.
This is what I did:
1. Install packages: `php php-sqlite composer`
2. [Uncomment the following lines in: `/etc/php/php.ini`](https://wiki.archlinux.org/index.php/PHP#Sqlite)
```
extension=pdo_sqlite.so
extension=sqlite3.so
```
3. Run `sh setup.sh` script in `the-majest-of-vuejs-2/api/stories` directory
4. You should see the json for stories at http://localhost:3000/api/stories
