### ISSUE TITLE
Webpack templates additional question

### ISSUE THREAD

**Issue by jcerdan** [hootlex/the-majesty-of-vuejs-2#23]
This is about part III: Webpack templates:
vue-cli => creating project from template webpack asks a question not
included in your book:

vue init webpack blablabla
...
? Vue build 
> Runtime + Compiler
> Runtime-only

Could you include the explanations about this option 'Vue build' in your
next book update?

**Comment by pongoman** [comment]
Hi @jcerdan,

The vue-cli tool lets you choose your build:

![vue-build-vue-cli](https://cloud.githubusercontent.com/assets/14333747/24406902/2c2331d8-13d2-11e7-9f57-a7d35d7b9d94.png)

In case you missed it you can find some explanations in the official [guide of Vue](https://vuejs.org/v2/guide/installation.html#Explanation-of-Different-Builds) regarding different builds.
Note that: _The CLI assumes prior knowledge of Node.js and the associated build tools._

 

Thank you for suggesting to include these explanations we will consider this.
Cheers
