### ISSUE TITLE
npm run dev on chapter 16+ code not working

### ISSUE THREAD

**Issue by gwvt** [hootlex/the-majesty-of-vuejs-2#26]
npm run dev does not work on code from chapters 16+, getting error messages as below.
I'm running node 7.8.0 and npm 4.4.4 on macOS Sierra.
---
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 3@ dev: `cross-env NODE_ENV=development webpack-dev-server --inline --hot`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the 3@ dev script 'cross-env NODE_ENV=development webpack-dev-server --inline --hot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the 3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development webpack-dev-server --inline --hot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 3
npm ERR! There is likely additional logging output above.

**Comment by hootlex** [comment]
Did you run `npm install` first?

**Comment by gwvt** [comment]
Yes.

**Comment by pongoman** [comment]
Right thank you for pointing that out.

Updated older versions.

Closing

**Comment by gwvt** [comment]
Thank you.
