### ISSUE TITLE
Broken Links in Introduction

### ISSUE THREAD

**Issue by octoquad** [hootlex/the-majesty-of-vuejs-2#29]
Hi,

For the About Vue.js, Vue.js Overview, link 2 currently points to http://vuejs.org/guide/overview.html which results in a 404. This should probably be updated to https://vuejs.org/v2/guide/.

The second one is for the Learning Curve section and link 5. This currently points to a non-existent page as well: https://angular.io/docs/js/latest/quickstart.html which needs to point to https://angular.io/guide/quickstart. However the quick start guide on the angular web site does not seem that verbose as described in this section. Perhaps this sections is irrelevant now and can be removed due to the new Angular CLI?

Thanks

**Comment by pongoman** [comment]
Hi,

I have updated those links in the introduction section. Thank you for bringing this to our attention :)
