### ISSUE TITLE
Custom filter using library cap 6.3

### ISSUE THREAD

**Issue by Mdpproduction** [hootlex/the-majesty-of-vuejs-2#3]
Goog evening guys,
in the tip of page 66, there's something that i think need to be updated:

```
...
<button @click="order = order * -1">Reverse Order</button>
```

but we're filtering the array using lodash ._orderBy method like that:

```
<li v-for="story in _.orderBy(stories, ['upvotes'], [order])">
...
```

But now, **order** is a string, '**desc**' or '**asc**'. And, on the click event is setted the older setup from previous example. I'm right ?

**Comment by pongoman** [comment]
Hello @Mdpproduction ,

You are right, I will fix this example to serve its purpose. Thanks for bringing this to my attention.
