### ISSUE TITLE
Incorrect link on book on page 172

### ISSUE THREAD

**Issue by abkrim** [hootlex/the-majesty-of-vuejs-2#32]
Hi.

Example for chapter with axios, not show code of book, (use.$http.patch instead asios.get)

https://github.com/hootlex/the-majesty-of-vuejs-2/blob/master/codes/chapter12/app.js

I'm reading trasnlate book of spanish.

Also, I try to get example with axios, wlaking trought github, but I don't see.

Also, if I use code of book fails:

```
fetchStories: function() {
            var vm = this;
            axios.get('http://storiesapi.test/api/stories') // my develop domain
                .then(function (response) {
                    var storiesReady = response.data.map(function (story) {
                        story.editing = false;
                        return story;
                    })
                    Vue.set(vm, 'stories', storiesReady)
                    // vm.stories = response.data
            })
        },
```
Get error:
```
TypeError: response.data.map is not a function
[Learn More]
```
Best regards

**Comment by abkrim** [comment]
Sorry. I apologize for issue.

Not see, ``response.data.map``corect is ``response.data.data.map``

**Comment by pongoman** [comment]
Hi, did you manage to solve your issue? If there are any errors in Spanish translation please create a new issue. Thanks

**Comment by abkrim** [comment]
Yes. Issue it's solved after re-read code, and I see incorrect code.

Respect link, I think link for this lesson it's not correct because show code for use vur-resource instead Axios, but I thin that it's not problem on Spanish version. I'm looking for correct code of chapter, and I not see on repo.

Best regards.
