### ISSUE TITLE
Spanish Translation: Page 236 src/main.js incorrect

### ISSUE THREAD

**Issue by abkrim** [hootlex/the-majesty-of-vuejs-2#33]
Hi. Another point of break, for beginners that read your book. (I'm rookie)

Also, book advance, and any point for see error on git or references. That is difficult for beginner.

In translation:

src/main.js
```
import Vue from 'vue'
import VueRouter from 'vue-router'
import Hello from '../src/components/Hello.vue'
import Login from '../src/components/Login.vue”
```
Correct
```
import Vue from 'vue'
import App from './App'
import VueRouter from 'vue-router'
import Hello from '../src/components/Hello.vue'
import Login from '../src/components/Login.vue”
```

If not import App, cna't transpiling because App is not imported.

```
ReferenceError: App is not defined
```

Best regards

**Comment by pongoman** [comment]
Hi, thank for pointing this out. I will notify the Spanish translators about the issue.
