### ISSUE TITLE
Page 94 - possible correction

### ISSUE THREAD

**Issue by rydurham** [hootlex/the-majesty-of-vuejs-2#4]
Hello! Thank you for this excellent book.   

I think the "event" parameter is missing from the vote function on page 94.

```
methods: {
    vote: function (event) {
        console.log(event)
        this.votes++ 
        this.$emit('voted')
    }
}
```

**Comment by pongoman** [comment]
You are right, it needs the "event" in order for it to display the events correctly on browsers consoles (not only chrome). Thank you for taking time to note this.
