### ISSUE TITLE
Page 216, mistake for extension of Famous component

### ISSUE THREAD

**Issue by Mdpproduction** [hootlex/the-majesty-of-vuejs-2#9]
Hi guys,
at page 216, in the example component, we can omitted the '.vue' extension from Famous, at import statment ?

**Comment by pongoman** [comment]
Hello @Mdpproduction ,

It is actually the same here, both `'./Famous.vue'` , and `'./Famous'` work, but sometimes you may find that is necessary to have the `'.vue'` extension.
